import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import AuthProvider from '@/context/AuthProvider'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
export const metadata = {
  title: 'Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex flex-col  py-2 px-4  bg-blue-900 text-white justify-between`}>
        <AuthProvider>
        <div className="flex h-screen">
          <Navbar />
          <div className='bg-white flex p-2 flex-1 flex-row mr-2 mb-2 rounded-lg text-black'>
            {children}
          </div>
        </div>  
          <Footer/>
        </AuthProvider>
      </body>
    </html>
  )
}
