"use client"
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import AuthProvider from '@/context/AuthProvider'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { useState } from 'react'

// export const metadata = {
//   title: 'Ecommerce',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [navIsOpen, setNavIsOpen] = useState(false)
  const handleNavigation = () => {
    setNavIsOpen(!navIsOpen)
  }
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AuthProvider>
        <div className="flex flex-col h-screen">
          <div className='flex flex-row h-screen  bg-gray-200 justify-between w-full text-black'>
            <Navbar show={navIsOpen} />
            <button onClick={handleNavigation} className="self-start px-1">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 5.25h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5" />
              </svg>
            </button>
            {children}
          </div>
          <Footer/>
        </div>  
        </AuthProvider>
      </body>
    </html>
  )
}
